#!/bin/bash

if [[ $(id -u) == 0 ]]; then
  BASE_DIR="/etc/upcli"
else
  BASE_DIR="$HOME/.config/upcli"
fi

echo "------------------------------"
echo "|     # Install UPCLI #      |"
echo "| UPCLI by UG                |"
echo "| Copyright belongs to Allah |"
echo "------------------------------"

## Checking dependencies
echo ""
echo "checking dependencies.."
echo ""
if ! which which > /tmp/upcli-output; then
  echo "please install which package and then reinstall upcli.."
  echo "example (centos): yum install which -y"
  echo "exiting.."
  exit 1
fi
if ! which shc > /tmp/upcli-output; then
  echo "please install shc package and then reinstall upcli.."
  echo "example (centos): yum install shc -y"
  echo "example (ubuntu): apt install shc -y"
  exit 1
fi
if ! which jq > /tmp/upcli-output; then
  echo "please install jq package and then reinstall upcli.."
  echo "example (centos): yum install jq -y"
  echo "example (ubuntu): apt install jq -y"
  exit 1
fi
if ! which crontab > /tmp/upcli-output; then
  echo "please install crontab package and then reinstall upcli.."
  echo "example (centos): yum install cronie -y"
  echo "example (ubuntu): apt install cron -y"
  exit 1
fi
if ! which gzip > /tmp/upcli-output; then
  echo "please install gzip package and then reinstall upcli.."
  echo "example (centos): yum install gzip -y"
  echo "example (ubuntu): apt install gzip -y"
  exit 1
fi
if ! which bc > /tmp/upcli-output; then
  echo "please install bc package and then reinstall upcli.."
  echo "example (centos): yum install bc -y"
  echo "example (ubuntu): apt install bc -y"
  exit 1
fi

## Create upcli dir
if [[ ! -d $BASE_DIR/scripts ]]; then
  mkdir -p $BASE_DIR/scripts
fi
if [[ ! -d $BASE_DIR/backups ]]; then
  mkdir -p $BASE_DIR/backups
fi
if [[ ! -d $BASE_DIR/disabled ]]; then
  mkdir -p $BASE_DIR/disabled
fi

## Download template file
curl -o $BASE_DIR/backup-script.template https://raw.githubusercontent.com/deadlyug/upcli/v0.1.5-beta/backup-script.template -D /tmp/upcli-output
if ! cat /tmp/upcli-output | grep -e "200" > /tmp/upcli-output1; then
  if [[ -d $BASE_DIR ]]; then
    rm -rf $BASE_DIR
  fi
  echo ""
  echo "installation failed.."
  echo "read log at /tmp/upcli-output"
  echo "please retry.."
  exit 1
fi

curl -o $BASE_DIR/config.template https://raw.githubusercontent.com/deadlyug/upcli/v0.1.5-beta/config.template -D /tmp/upcli-output
if ! cat /tmp/upcli-output | grep -e "200" > /tmp/upcli-output1; then
  if [[ -d $BASE_DIR ]]; then
    rm -rf $BASE_DIR
  fi
  echo ""
  echo ""
  echo "installation failed.."
  echo "read log at /tmp/upcli-output"
  echo "please retry.."
  exit 1
fi

## Download script
if [[ $(id -u) == 0 ]]; then
  curl -o /bin/upcli https://raw.githubusercontent.com/deadlyug/upcli/v0.1.5-beta/upcli -D /tmp/upcli-output
  if ! cat /tmp/upcli-output | grep -e "200" > /tmp/upcli-output1; then
    if [[ -d $BASE_DIR ]]; then
      rm -rf $BASE_DIR
    fi
    echo ""
    echo "installation failed.."
    echo "please retry.."
    exit 1
    fi
  chmod +x /bin/upcli
else
  curl -o ./upcli https://raw.githubusercontent.com/deadlyug/upcli/v0.1.5-beta/upcli -D /tmp/upcli-output
  if ! cat /tmp/upcli-output | grep -e "200" > /tmp/upcli-output1; then
    if [[ -d $BASE_DIR ]]; then
      rm -rf $BASE_DIR
    fi
    echo ""
    echo "installation failed.."
    echo "please retry.."
    exit 1
  fi
  sudo mv ./upcli /usr/bin/upcli
  sudo chmod +x /usr/bin/upcli
fi

## Create cronjob
crontab -l | sed 's/.*upcli.*//' | crontab -
crontab -l | sed 's/.*upcli.*//' | crontab -
crontab -l | sed 's/.*upcli.*//' | crontab -
crontab -l | sed 's/.*upcli.*//' | crontab -
crontab -l | sed '/^$/d'| crontab -
{ crontab -l; echo "@yearly $(which upcli) --run all yearly"; } | crontab -
{ crontab -l; echo "@monthly $(which upcli) --run all monthly"; } | crontab -
{ crontab -l; echo "@weekly $(which upcli) --run all weekly"; } | crontab -
{ crontab -l; echo "@daily $(which upcli) --run all daily"; } | crontab -

echo ""
echo "success, upcli installed.."
