#!/bin/bash

if [[ $(id -u) == 0 ]]; then
  BASE_DIR="/etc/upcli"
else
  BASE_DIR="$HOME/.config/upcli"
fi

echo "------------------------------"
echo "|          # UPCLI #         |"
echo "| UPCLI by UG                |"
echo "| Copyright belongs to Allah |"
echo "------------------------------"

echo ""
echo "uninstalling upcli.."

if [[ -d $BASE_DIR ]]; then
  rm -rf $BASE_DIR
fi

upcli=$(which upcli)
if [[ -f $upcli ]]; then
  if [[ $(id -u) == 0 ]]; then
    rm -rf $upcli
  else
    sudo rm -rf $upcli
  fi
fi

## Delete cronjob
crontab -l | sed 's/.*upcli.*//' | crontab -
crontab -l | sed 's/.*upcli.*//' | crontab -
crontab -l | sed 's/.*upcli.*//' | crontab -
crontab -l | sed 's/.*upcli.*//' | crontab -
crontab -l | sed '/^$/d'| crontab -

echo ""
echo "upcli uninstalled successfully.."
